configform:
  path: '/myform'
  defaults:
    _form: 'Drupal\configform\Form\SimpleConfigForm'
    _title: 'Custom Module for building forms'
  requirements:
    _permission: 'access content'       
configform.simpleform:
  path: '/mysimpleform'
  defaults:
    _form: 'Drupal\configform\Form\SimpleForm'
    _title: 'Custom Module for building normal forms'
  requirements:
    _permission: 'access content'
configform.hello_drupal:
  path: '/hello_drupal'
  defaults:
    _controller: 'Drupal\configform\Controller\HelloController::content'
    _title: 
  requirements:
    _permission: 'access content'  
configform.hello_world:
  path: '/hello_world' 
  defaults:
    _controller: 'Drupal\configform\Controller\HelloWorld::content'  
    _title:
  requirements:
    _permission: 'access content'  
hello.dynamic_user:
  path: '/hello/{name}'
  defaults:
    _controller: 'Drupal\configform\Controller\HelloDynamic::content'
    _title: 'Hello'
  requirements:
    _permission: 'rahul hello route'   
hello.author:
  path: '/para/{nodeid}'          
  defaults:
    _controller: 'Drupal\configform\Controller\HelloAuthor::content'  
    _title: 'Hello'
  requirements:
    _permission: 'rahul hello route'  