<?php
/**
* @file
* Contains \Drupal\article\Plugin\Block\ArticleBlock.
*/
namespace Drupal\configform\Plugin\Block;
use Drupal\Core\Block\BlockBase;
use Drupal\Core\Form\FormInterface;
/**
* Provides a 'article' block.
*
* @Block(
*   id = "custom_block",
*   admin_label = @Translation("Article block"),
*   category = @Translation("Custom block")
* )
*/
class ArticleBlock extends BlockBase {
 /**
  * {@inheritdoc}
  */
 public function build() {
   $form = \Drupal::formBuilder()->getForm('Drupal\configform\Form\SimpleForm');
   return $form;
  }
}
